name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse flavors from JSON
        id: set-flavors
        run: |
          FLAVORS_JSON=$(cat flavors.json)
          # Extract dynamic platforms based on the presence of `platforms` in each flavor
          PLATFORMS_LIST=$(echo "$FLAVORS_JSON" | jq -r '.flavors | to_entries[] | select(.value.is_upload == true) | .value.platforms | .[]')
          
          # Create array of platforms (unique and in proper format)
          PLATFORMS_ARRAY=$(echo "$PLATFORMS_LIST" | sed 's/^/"/;s/$/"/' | paste -sd "," -)
          PLATFORMS_ARRAY="[$PLATFORMS_ARRAY]"

          # Debug print
          echo "Flavors to build platform: $PLATFORMS_ARRAY"

          # Set the platforms variable using environment file (NEW METHOD)
          echo "PLATFORMS=$PLATFORMS_ARRAY" >> $GITHUB_ENV

  build:
    needs: parse
    runs-on: macos-latest
    steps:
      - name: Debug Print Platforms
        run: |
          # Ensure the PLATFORMS environment variable is set and echo it
          echo "PLATFORMS_LIST: ${{ env.PLATFORMS }}"

          # Now parse it from JSON format using 'fromJson' to convert it into a list
          if [ -n "${{ env.PLATFORMS }}" ]; then
            echo "Parsed PLATFORMS_LIST: ${{ fromJson(env.PLATFORMS) }}"
          else
            echo "PLATFORMS is not set correctly!"
          fi

